theweather/urls.py
from django.urls import path

from . import views


app_name = "theweather"
urlpatterns = [
    path("graficos/", views.IndexView, name="graficos"),
    path('home/', views.testeIndexView, name='home'),
    path('cadastrar/', views.IndexViewCadastrarLogin,
         name='IndexViewCadastrarLogin'),
    path('', views.IndexViewLogin, name='IndexViewLogin'),
]

weatherapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static


urlpatterns = [
    path("", lambda request: redirect('theweather/', permanent=True)),
    path("theweather/", include("theweather.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

theweather/models.py
import datetime
from django import forms
from django.utils import timezone
import django.utils
import time

theweather/forms.py
from django import forms


class ChoiceForm(forms.Form):
    choice_text = forms.CharField(max_length=100, label="Nome Escolha")


class QuestionForm(forms.Form):
    question_text = forms.CharField(max_length=100, label="Questão")
    teste = forms.IntegerField(label="Teste")


class DadosMetereologicosForm(forms.Form):
    temperatura = forms.IntegerField()
    umidade = forms.DecimalField()


class RegiaoForm(forms.Form):
    regiao = forms.CharField(max_length=100)
    cidade = forms.CharField(max_length=100)


class CadastoForm(forms.Form):
    nome = forms.CharField(max_length=100, label="Nome",
                           widget=forms.TextInput(attrs={"placeholder": "Nome"}))
    email = forms.CharField(max_length=100, label="Email",
                            widget=forms.TextInput(attrs={"placeholder": "Email"}))
    senha = forms.CharField(max_length=100, label="Senha",
                            widget=forms.TextInput(attrs={"placeholder": "Senha", "type": "password", "minlength": "8"}))


class ValidaLoginForm(forms.Form):
    email = forms.CharField(max_length=100, label="Email",
                            widget=forms.TextInput(attrs={"placeholder": "Email"}))
    senha = forms.CharField(max_length=100, label="Senha",
                            widget=forms.TextInput(attrs={"placeholder": "Senha", "type": "password", "minlength": "8"}))

theweather/views.py
import os
from django.shortcuts import render, redirect
from django.views import generic
from .forms import *
from pymongo import MongoClient
from bson import Decimal128
from django.urls import reverse
import datetime
import decimal
from bson.objectid import ObjectId
from dotenv import load_dotenv
from django.contrib import messages
import smtplib
import email.message

# Create your views here.

MONGODB_URI = os.environ['MONGODB_URI']
OPTIONS = os.environ['OPTIONS']

print(MONGODB_URI+OPTIONS)
client = MongoClient(
    MONGODB_URI+OPTIONS)
db = client.WheatherDB
regiao = db.regiao
dados_metereologicos = db.dados_metereologicos
usuario = db.usuario


def IndexView(request):
    template_name = "theweather/index.html"
    context_object_name = "latest_regiao_list"

    lookup = {"$lookup": {"from": "dados_metereologicos",
                          "localField": "_id",
                          "pipeline": [{"$sort": {"dt_criacao": 1}}],
                          "foreignField": "id_regiao",
                          "as": "dadosM"}}

    project = {"$project": {'_id': 0, 'dadosM._id': 0,
                            'dadosM.id_regiao': 0, 'dadosM.regiao': 0}}

    pipeline = [lookup, project]

    results = list(regiao.aggregate(pipeline))
    print(results)

    resultsFilter = []

    for dados in results:
        for maps in dados['dadosM']:
            for key, value in maps.items():
                if (type(value) == Decimal128):
                    maps[key] = float(str(maps[key]))
                elif (type(value) == datetime.datetime):
                    maps[key] = maps[key].strftime('%Y-%m-%d %H:%M:%S')
        resultsFilter.append(dados)

    """Return the last five published questions."""
    return render(request, template_name, {context_object_name: resultsFilter})


def enviar_email(emailname, nome, assunto, corpo):
    corpo_email = f"""
        Email: {emailname} <br>
        Nome: {nome} <br>
        {corpo}
    """

    msg = email.message.Message()
    msg['Subject'] = assunto
    msg['From'] = 'teagames2023@gmail.com'
    msg['To'] = 'teagames2023@gmail.com'
    password = 'mjiqlvpsnvbjujot'
    msg.add_header('Content-Type', 'text/html')
    msg.set_payload(corpo_email)

    s = smtplib.SMTP('smtp.gmail.com: 587')
    s.starttls()
    # Login Credentials for sending the mail
    s.login(msg['From'], password)
    s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
    print('Email enviado')


def testeIndexView(request):
    template_name = "theweather/home.html"
    context_object_name = "latest_regiao_list"

    lookup = {"$lookup": {"from": "dados_metereologicos",
                          "localField": "_id",
                          "pipeline": [{"$sort": {"dt_criacao": -1}}, {"$limit": 1}],
                          "foreignField": "id_regiao",
                          "as": "dadosM"}}

    project = {"$project": {'_id': 0, 'dadosM._id': 0,
                            'dadosM.id_regiao': 0, 'dadosM.regiao': 0}}

    pipeline = [lookup, project]

    results = list(regiao.aggregate(pipeline))
    print(results)

    resultsFilter = []

    for dados in results:
        for maps in dados['dadosM']:
            for key, value in maps.items():
                if (type(value) == Decimal128):
                    maps[key] = float(str(maps[key]))
                elif (type(value) == datetime.datetime):
                    maps[key] = maps[key].strftime('%Y-%d-%m %H:%M:%S')
        resultsFilter.append(dados)

    if request.method == 'POST':
        print(request.POST)
        print(request.POST['nome'])
        enviar_email(request.POST['email'], request.POST['nome'],
                     request.POST['assunto'], request.POST['messagem'])
    return render(request, template_name, {context_object_name: resultsFilter})


def IndexViewCadastrarLogin(request):
    form_Cadastro = CadastoForm()
    template_name = "theweather/cadastro.html"
    print("Cadastrado com Sucesso !")

    if request.method == 'POST':
        form_Cadastro = CadastoForm(request.POST)
        if form_Cadastro.is_valid():
            input_Cadastro = form_Cadastro.cleaned_data
            usuario.insert_one(input_Cadastro)
            print(input_Cadastro)
            messages.success(request, message='Cadastro feito com sucesso!!')
            return redirect(reverse('theweather:IndexViewLogin'))
    else:
        form_Cadastro = CadastoForm()

    """Return the last five published questions."""
    return render(request, template_name,  {'form': form_Cadastro})


def IndexViewLogin(request):
    template_name = "theweather/login.html"
    print("teste")

    if request.method == 'POST':
        form_Login = ValidaLoginForm(request.POST)
        if form_Login.is_valid():
            input_Login = form_Login.cleaned_data
            resultado = usuario.find_one(input_Login)

            if (resultado is not None):
                print("Roteia para Home")
                return redirect(reverse('theweather:home'))
            else:
                print("Email ou senha errado!")
                form_Login = ValidaLoginForm()
                messages.success(request, message='Email ou senha errado!')

            print(input_Login)
            print(resultado)
    else:
        form_Login = ValidaLoginForm()

    """Return the last five published questions."""
    return render(request, template_name,  {'form': form_Login})

theweather/templates/testehome/index.html
{% extends "../theweather/base.html" %}
{% load static %}



{% block content %}
  <div id="banner" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="jumbotron">
          <h1 class="small">Bem-vindo ao <span class="bold">The Weather </span></h1>
          <p class="big">MONITORANDO AS TEMPERATURAS LOCAIS</p>
        </div>
      </div>
    </div>
  </div>
 
  <div class="cta-1">
    <div class="container">
      <div class="row text-center white">
        <h1 class="cta-title">The Weather</h1>
        <p class="cta-sub-title">Site de Monitoramento Climático Utilizando IoT</p>
      </div>
    </div>
  </div>

  <div id="service" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="page-title text-center">
          <h1>Temperatura Atual</h1>
          <p>Medição atual da cidade Patos de Minas<br>Região: Unipam</p>
          <hr class="pg-titl-bdr-btm"></hr>
        </div>
        <div class="col-md-6">
          <div id="chart1">
          </div>
        </div>
        <div class="col-md-6">
          <div id="chart2">
          </div>
        </div>
      </div>
    </div>
  </div>


  <div id="about" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="page-title text-center">
          <h1>Conheça nossa equipe</h1>
          <p>Bravos Guerreiros<br>Se junte a nós nesse projeto.</p>
          <hr class="pg-titl-bdr-btm"></hr>
        </div>
        <div class="autoplay">
          <div class="col-md-6">
            <div class="team-info">
              <div class="img-sec">
                <img src="{% static 'img/agent1.jpg' %}" class="img-responsive">
    
              </div>
              <div class="fig-caption">
                <h3>João Augusto</h3>
                <p class="marb-20">Trabalhador de sinaleiro</p>
                <p>Follow me:</p>
                <ul class="team-social">
                  <li class="bgblue-dark"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="bgred"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="bgblue-light"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="bgblue-dark"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="team-info">
              <div class="img-sec">
                <img src="{% static 'img/agent2.jpg' %}" class="img-responsive">
              </div>
              <div class="fig-caption">
                <h3>Hyure</h3>
                <p class="marb-20">DBA</p>
                <p>Follow me:</p>
                <ul class="team-social">
                  <li class="blue-dark"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="red"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="blue-light"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="blue-dark"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="team-info">
              <div class="img-sec">
                <img src="{% static 'img/agent3.jpg' %}" class="img-responsive">
              </div>
              <div class="fig-caption">
                <h3>Ricardo Balbino</h3>
                <p class="marb-20">Front-End</p>
                <p>Follow me:</p>
                <ul class="team-social">
                  <li class="blue-dark"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="red"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="blue-light"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="blue-dark"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="team-info">
              <div class="img-sec">
                <img src="{% static 'img/agent4.jpg' %}" class="img-responsive">
              </div>
              <div class="fig-caption">
                <h3>Eduardo Cipriano</h3>
                <p class="marb-20">Front-End</p>
                <p>Follow me:</p>
                <ul class="team-social">
                  <li class="blue-dark"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="red"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="blue-light"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="blue-dark"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="page-title text-center">
          <h1>Envie sua Dúvida</h1>
          <p>Nosso suporte pode responder as suas dúvidas ou sugestões da melhor maneira<br>Venha nós ajudar </p>
          <hr class="pg-titl-bdr-btm"></hr>
        </div>
        <div id="sendmessage">Enviado !!!</div>
        <div id="errormessage"></div>

        <div class="form-sec">
          <form action="" method="post" role="form" class="contactForm">
            {% csrf_token %}
            <div class="col-md-4 form-group">
              <input type="text" name="nome" class="form-control text-field-box" id="name" placeholder="Seu Nome" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
              <div class="validation"></div>
            </div>
            <div class="col-md-4 form-group">
              <input type="email" class="form-control text-field-box" name="email" id="email" placeholder="Seu Email" data-rule="email" data-msg="Please enter a valid email" />
              <div class="validation"></div>
            </div>
            <div class="col-md-4 form-group">
              <input type="text" class="form-control text-field-box" name="assunto" id="subject" placeholder="Sugestão" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validation"></div>
            </div>
            <div class="col-md-12 form-group">
              <textarea class="form-control text-field-box" name="messagem" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Descreva sua sugestão"></textarea>
              <div class="validation"></div>

              <button class="button-medium" id="contact-submit" type="submit" name="contact">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>



  <footer class="footer section-padding">
    <div class="container">
      <div class="row">
        <div style="visibility: visible; animation-name: zoomIn;" class="col-sm-12 text-center wow zoomIn">
          <h3>Follow us on</h3>
          <div class="footer_social">
            <ul>
              <li><a class="f_facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="f_twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="f_google" href="#"><i class="fa fa-google-plus"></i></a></li>
              <li><a class="f_linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!--- END COL -->
      </div>
      <!--- END ROW -->
    </div>
    <!--- END CONTAINER -->
  </footer>
  <!--FOOTER END-->

  <div class="footer-bottom">
    <div class="container">
      <div style="visibility: visible; animation-name: zoomIn;" class="col-md-12 text-center wow zoomIn">
        <div class="footer_copyright">
          <p> © Copyright, All Rights Reserved.</p>
          <div class="credits">
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}


{% block script %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

<script>
  var dadosMregiao = {{latest_regiao_list|safe}}
  console.log(dadosMregiao)
  

  count = 1
  for(var i in dadosMregiao){
    console.log(dadosMregiao[i])
    var dadosM = dadosMregiao[i]['dadosM']
    console.log(dadosM)
    var options = {
      chart: {
          height: 350,
          type: 'radialBar',
      },
        plotOptions: {
        radialBar: {
          dataLabels: {
            value: {
              show: true,
              fontSize: '14px',
              formatter: function (val) {
                return val
              }
            }
          }
        }
      },
      series: [dadosM[0]['temperaturaBanco']],
      labels: ['Temeperatura'],
    }


    var options2 = {
      chart: {
          height: 350,
          type: 'radialBar',
      },
        plotOptions: {
        radialBar: {
          dataLabels: {
            value: {
              show: true,
              fontSize: '14px',
              formatter: function (val) {
                return val + '%'
              }
            }
          }
        }
      },
      series: [dadosM[0]['umidadeBanco']],
      labels: ['Umidade'],
    }
    
    console.log(`#chart${count}`)
    var chart = new ApexCharts(document.querySelector(`#chart${count}`), options);
    count++
    var chart2 = new ApexCharts(document.querySelector(`#chart${count}`), options2);
    
    chart.render();
    chart2.render();
  }
  
</script>
{% endblock %}

theweather/templates/theweather/base.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br" class=" js no-touch">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static '/img/IconsWeatherIcone.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600|Raleway:600,300|Josefin+Slab:400,700,600italic,600,400italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick-team-slider.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header>
      <div class="main-navigation navbar-fixed-top">
        <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand" href="{% url 'theweather:home' %}">The Weather</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'theweather:home' %}">Inicio</a></li>
                <li><a href="{% url 'theweather:graficos' %}">Gráficos</a></li>
                <li><a href="{% url 'theweather:IndexViewLogin' %}">Logout</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>

    {% block content %} {% endblock %}




    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    {% block script %} {% endblock %}
  </body>
</html>

theweather/templates/theweather/cadastro.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cadastro</title>
    <link rel="stylesheet" href="{% static 'css/style3.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static '/img/IconsWeatherIcone.ico' %}">
  </head>

  <body>
    <div class="main-login">
      <div class="left-login">
        <h1>THE WEATHER</h1>
        <img
          src="{% static 'IMG/server-animate.svg' %}"
          class="left-login-img"
          alt="Weather Animação"
        />
      </div>
      <form method="post" class="right-login">
        {% csrf_token %}
        <div class="card-login">
          <h1>CADASTRO</h1>
          {% for fm in form %}
          <div class="textfield">
            <label>{{fm.label}}</label>
            {{fm}}
          </div>
          {% endfor %}
          <button class="btn-login" type="submit">Cadastrar</button>
          <button
            class="btn-login"
            onclick="window.location='{% url 'theweather:IndexViewLogin' %}'"
          >
            VOLTAR
          </button>
        </div>
      </form>
    </div>
  </body>

  {% if messages %}
  {% for message in messages %}
   {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
  
  {% endfor %}
  
  {% endif %}
</html>

theweather/templates/theweather/index.html
{% extends "./base.html" %}
{% load static %}

{% block title %} The wheather {% endblock %} 

{%block content %}


</br>
</br>
</br>
</br>
</br>
</br>

<section id="graficos" class="container-fluid">
  <div class="row mb-4">
    <div class="page-title text-center">
      <h1>Gráficos Atuais</h1>
      <p>Medição atual da cidade Patos de Minas<br>Região: Unipam</p>
      <hr class="pg-titl-bdr-btm"></hr>
      <button class="button-medium" onClick="location.reload();">Atualizar</button>
    </div>
    <div class="col-md-6">
      <div class="chart-container" style="aspect-ratio: 2">
        <canvas id="myChart"></canvas>
      </div>
    </div>
    <div class="col-md-6">
      <div class="chart-container" style="aspect-ratio: 2">
        <canvas id="myChart2"></canvas>
      </div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-md-6">
      <div class="chart-container" style="aspect-ratio: 2">
        <canvas id="myChart3"></canvas>
      </div>
    </div>
    <div class="col-md-6">
      <div class="chart-container" style="aspect-ratio: 2">
        <canvas id="mixedChart"></canvas>
      </div>
    </div>
  </div>
</section>
</br>
</br>
</br>
<div class="container-fluid mt-4">
  <iframe class="mt-6" src="http://3.92.144.248:1880/ui/#!/0?socketid=6LXaFCqK3T9SFzFSAAFo" title="description" width="100%" height="800"></iframe>
</div>





{% endblock content %}


{% block script %}
<script src="{% static 'script.js' %}"></script>
<script>
  const pointImage = new Image(40,40);
  pointImage.src = "{% static '/img/IconsWeather.png' %}";


  var dadosMregiao = {{latest_regiao_list|safe}}
  var datasetsUmidade = []
  var datasetsTemperatura = []
  var temperaturaUmidae = []
  var chartLineBar = []

  var dadosMregiao2 = {}

  for(var x in dadosMregiao){
    var dictU = {"borderWidth" : 5}
    var dictT = {"borderWidth" : 5}
    var dictUT = {}


    var dictBar = {
      label: 'Temperatura',
      type: 'bar',
      backgroundColor: '#2f27ce',
      borderColor: '#2f27ce',
      borderWidth: 5,
      order: 1
    }

    var dictLine = {
      elements:{
        point:{
          pointStyle: [pointImage],
          hitRadius: 20,
          hoverRadius: 20
        }
      },
      pointRadius: 10,
      label: 'Umidade',
      type: 'line',
      fill: false,
      borderColor: '#2f27ce',
      borderWidth: 5,
      order: 0
    }


    dictBar.data = []
    dictLine.data = []

    dictT.label = dadosMregiao[x]['regiao']
    dictU.label = dadosMregiao[x]['regiao']
    dictUT.nome = dadosMregiao[x]['regiao']
    dictUT.data = []

    dadosMregiao2[dadosMregiao[x]['regiao']] = []

    var dadosM = dadosMregiao[x]['dadosM'];


    var temperatura = dadosM.map(x => ({"y": x.temperaturaBanco, "x": x.dt_criacao}))
    dadosMregiao2[dadosMregiao[x]['regiao']].push({"type": "line","borderWidth" : 5,"label": "Temperatura", "data": temperatura})

    var umidade = dadosM.map(x => ({"y": x.umidadeBanco, "x": x.dt_criacao}))
    dadosMregiao2[dadosMregiao[x]['regiao']].push({"type": "line","borderWidth" : 5, "label": "Umidade", "data": umidade})

    dictBar.data = temperatura

    dictLine.data = umidade

    dictU.data = dadosM
    dictT.data = dadosM

    dictU.parsing = {
      xAxisKey: 'dt_criacao',
      yAxisKey: 'umidadeBanco'
    }

    dictT.parsing = {
      xAxisKey: 'dt_criacao',
      yAxisKey: 'temperaturaBanco'
    }

    datasetsUmidade.push(dictU)
    datasetsTemperatura.push(dictT)
    chartLineBar.push(dictLine)
    chartLineBar.push(dictBar)

  }

  console.log(datasetsUmidade)
  console.log(dadosMregiao2)


  const ctx = document.getElementById("myChart");
  const ctx2 = document.getElementById("myChart2");
  var ctx3 = document.getElementById("mixedChart").getContext("2d");
  const ctx4 = document.getElementById("myChart3");

  graficoLine(ctx, datasetsUmidade, "Gráfico Umidade (2023)",20)
  graficoLine(ctx2, datasetsTemperatura,"Gráfico Temperatura (2023)",20)

  //criaGraficosUmTemp(dadosMregiao2)
  graficoLine(ctx4, dadosMregiao2['Unipam'],`Gráfico Temperatura/Umidade Unipam (2023)`,20)



  var data = {
    datasets: chartLineBar
  };

  var options = {
    responsive: true,
    scales: { 
      x: {
          type: 'time',
          time: {
            unit: 'minute', // Use 'minute' for minute granularity
            displayFormats: {
              minute: 'dd/MM HH:mm' // Format for displaying minutes
            },
            tooltipFormat: 'dd/MM HH:mm'
          }
      },
      y: {
        beginAtZero: true,
      },
  }
  };

  var mixedChart = new Chart(ctx3, {
    type: "bar",
    data: data,
    options: options,
  });

 
</script>
{% endblock %}

theweather/templates/theweather/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static '/img/IconsWeatherIcone.ico' %}">
  </head>
  <body>
    <div class="main-login">
      <div class="left-login">
        <h1>
          The Weather <br />
          Medições Meteorológicas
        </h1>
        <img
          src="{% static 'IMG/Weather.svg' %}"
          class="left-login-img"
          alt="Weather Animação"
        />
      </div>

      <div class="right-login">
        <div class="card-login">
          <form method="post" class="right-login">
            <div class="card-form">
            {% csrf_token %}
            <h1 style="color: #ffff;">LOGIN</h1>
            {% for fm in form %}
              <div class="textfield">
                <label>{{ fm.label }}</label>
                {{ fm }}
              </div>
            {% endfor %}
  
            <button class="btn-login" type="submit">
              LOGIN
            </button>
          </div>
          </form>

          <button class="btn-login" onClick="window.location='{% url 'theweather:IndexViewCadastrarLogin' %}'">
            CADASTRO
          </button>
        </div>
      </div>
    </div>
  </body>

  {% if messages %}
{% for message in messages %}
 {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

{% endfor %}

{% endif %}
</html>